### ISSUE TITLE
Windows speech recognition macros Windows 11 error 

### ISSUE THREAD

**Issue by amirf147** [leeorhelps/SpeechBird#1]
After successfully signing the macros file, I get an error when trying to open the macros:

![Screenshot 2022-12-01 205017](https://user-images.githubusercontent.com/7341565/205206942-f87f334c-069e-42e8-b2d1-8d25cdd5c86d.png)

![Screenshot 2022-12-01 210123](https://user-images.githubusercontent.com/7341565/205205991-a6d06041-6dd0-4d5c-bc1c-b1dbd4a2b38b.png)

I guess it has something to do with that character encoding. If I change the encoding to UTF-8 I get the following error:

![Screenshot 2022-12-01 204442](https://user-images.githubusercontent.com/7341565/205206361-62cc54fc-c5f7-4b94-b0f5-d389d5fee9b5.png)

**Comment by leeorhelps** [comment]
UTF-16 was needed to allow Hebrew chars, which I sometimes use in macros. 

I actually have a macro pack for VS Code if you want it, early alpha -- adds support for some C, HTML, Python...

That said, editing works much better in notepad, and it should be able to save the file correctly.

You might need to go to windows control panel -> regional -> encoding options to add proper support for UTF 16.

It's been a very long time since I added the support on my own system, can't remember exactly -- so would be great if you would care to get back and post how you solved it, so others can benefit.

**Comment by leeorhelps** [comment]
Oh, and you can just search for א or any other Hebrew char to find any Hebrew in the xml, and delete those lines -- should work with UTF 8 after. 


Final thought: Could also be the triple-period ("...") --- it has a single char UTF 16 symbol, and sometimes sneaks into code by auto correct etc...

Actually, it's probably this last one. You can just search for this char and replace it with three single "."'s

**Comment by amirf147** [comment]
Switching the encoding UTF-8 allows the file to be properly read. I've been just trying separate parts of the entire macros file as individual separate macros files. I got your clicks macros working. I was unable to get the macros working that use the 1to20. I guess that's what the error dialog is in reference to which was the last image in my post. I'm wondering if this could be a windows 11 issue and there's a different way to reference {[1to20.num]} now. I'm specifically talking about the before [1to20] emulation.

I also tried to create it like this but the same error pops up: 
![image](https://user-images.githubusercontent.com/7341565/205457409-a5809246-af4f-4561-a6c9-7331433430ff.png)

The error: 
![image](https://user-images.githubusercontent.com/7341565/205457503-87a25730-6aad-4ad4-973d-470631c3a11d.png)

**Comment by leeorhelps** [comment]
Would you like to post your version of the 1to20 rule?

**Comment by leeorhelps** [comment]
By the way, in the new version that I am working on, I am experimenting with having the numbering _after_ the action. So that would be "before [1to20]".

The idea is to reduce cognitive load further, and increase workflow speed -- which I am constantly trying to improve. The idea is that the user knows they want to move left, they don't need to say how many times while they are saying "left", rather, they can figure out the number while uttering the action.

**Comment by amirf147** [comment]
OK so 1to20 is a rule that you defined yourself? I thought it was a predefined thing in windows speech recognition. I guess you defined in this rule later in the document? I saw some reference to this rule later in the document but I don't yet understand how it works. Also, it looks like a lot of the information for speech recognition macros has been removed from the Microsoft web site. I did download the SAPI 5.1 sdk from their website and have been looking at the sapi.chm. Looks like there's a lot of reading that I need to do. Is there reason why my attempt at implementing the before command didnt work, as showed in image i uploaded. Do I have to create that rule myself? Where is that rule located in your file?

Also I'd appreciate anything you could send to amirf147@gmail.com

I would like the macro pack please.

Problem I have with your file after I was successfully able to sign it Is that it just crashes windows speech recognition macros. I also commented out sections that had a placeholder. This is why I would like to put it together piece by piece so I could figure out what the problem is

**Comment by amirf147** [comment]
These "--" , were coming up as errors in visual studio code and their removal was one of the things that allowed the document to get successfully signed later 
![Screenshot_20221205_113514](https://user-images.githubusercontent.com/7341565/206567714-ffc6e77f-5167-42ef-8e30-af6db0c00463.png)

**Comment by amirf147** [comment]
Here is an error dialog for the same error I think 
![Screenshot_20221205_111446](https://user-images.githubusercontent.com/7341565/206568419-cdca5941-2386-432e-a8c0-edd95995490f.png)

**Comment by amirf147** [comment]
Another thing I noticed is that after a few days I have to create a new signing certificate to sign new macros. I have not investigated the reproducibility of this error but whenever I get the error : 
![Screenshot_20221204_040343](https://user-images.githubusercontent.com/7341565/206569633-9a1b22a9-88f0-4c15-b3cc-0e8b7b0ba825.png)
Signing with a newly created signing certificate seems to be a fix for this

**Comment by leeorhelps** [comment]
Yes, every now and then a new signing certificate is required. Of course, you could change security settings to not need it certificates at all, but I do not recommend that at all.

I actually have a set of macros that help to write macros by voice, including signing. One of those macros is used to create a new signing certificate. Happy to share those if it helps.

**Comment by leeorhelps** [comment]
> Here is an error dialog for the same error I think 
> 
> ![Screenshot_20221205_111446](https://user-images.githubusercontent.com/7341565/206568419-cdca5941-2386-432e-a8c0-edd95995490f.png)
> 
> 

Thanks, noted. 

The double dash's are not an issue with WSR, only VS Code. Have you tried setting VS Code to a different type of syntax highlighting? Are you on XML?

**Comment by leeorhelps** [comment]
> OK so 1to20 is a rule that you defined yourself? I thought it was a predefined thing in windows speech recognition. I guess you defined in this rule later in the document? 

Yes. WSR does have a built in way of generating "number" rules, but I don't like it because: Slower runtime; it picks up variations of numbers ("one" and "once" and "first") etc -- but I use plurals for other things and want to differentiate them.
All rules are defined at the bottom of the file, after all the macros. Refer to the Table of Contents at the top?
I actually commented-out 11 thru 20 for most implementations, since I don't really need them, so future versions of this rule may be renamed to "1to10".

>I saw some reference to this rule later in the document but I don't yet understand how it works. Also, it looks like a lot of the information for speech recognition macros has been removed from the Microsoft web site. I did download the SAPI 5.1 sdk from their website and have been looking at the sapi.chm. Looks like there's a lot of reading that I need to do. 

Yeah. You can still find their WSR Lang doc file that they originally distributed, and a few resources online.  Documentation is weak, but WSR Macros is awesome and worth learning it's simple but powerful XML language.


>Is there reason why my attempt at implementing the before command didnt work, as showed in image i uploaded. Do I have to create that rule myself? Where is that rule located in your file?

Yeah -- "before" is a shortcut for "go back one word", and "before [1to20]" is "go back {[1to20]} words". 

Same for "after". The SpeechBird dialect works such that any of these statements, when said with an "s" at the end, moves + selects. So "after" moves a word forward. "Afters" selects next word. "Afters 5" selects next 5 words. This works for almost all my commands, eg. "Left" vs "Lefts", "3rd line" vs "3rd lines" -- one moves, the other moves + selects.

And putting the "s" at the start will click the mouse, then select accordingly. Eg. "sline" will click wherever mouse is pointing, select line. "Nope" corrects a word; "nopes 5" corrects last 5 words. "snope 3" corrects last 3 words starting from current mouse pointer location. 

> 
> 
> 
> Also I'd appreciate anything you could send to amirf147@gmail.com
> 
> 

I'll need sometime yo clean things up and put on GitHub. Until then, feel free to request anything and I'll send over. 

> 
> I would like the macro pack please.
> 
> 
> 
> Problem I have with your file after I was successfully able to sign it Is that it just crashes windows speech recognition macros. I also commented out sections that had a placeholder. This is why I would like to put it together piece by piece so I could figure out what the problem is 

I'm working on switching to environment variables instead of the placeholders. Then, editing the macro won't be needed anymore, just set the env vars on your machine and the macros should play along nicely. Someday soon...

**Comment by amirf147** [comment]
OK I'm using Autohotkey version 2. I think that's what was causing errors with your version of the clicks script. Based on your script, I created this modified version that works for Autohotkey version 2.

```
; A modification to the mouse drag script written by @leeorhelps in
; https://github.com/leeorhelps/SpeechBird 
#Requires AutoHotkey v2.0-beta

; #NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode "Input"  ; Recommended for new scripts due to its superior speed and reliability.
; SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory

;release Lmouse button if pressed, and drag
LSHIFT & F12:: 
{
MouseClick "left", , , , , "U"
Sleep 100
MouseClick "left", , , , , "D"
return 
}

;release Rmouse button if pressed, and drag
RSHIFT & F12::
{
MouseClick "right", , , , , "U"
Sleep 100
MouseClick "right", , , , , "D"
return
}

;release Lmouse and / or Rmouse buttons if pressed
F12::
{
if( GetKeyState("LButton") )
	MouseClick "left", , , , , "U"
if( GetKeyState("RButton") )
	MouseClick "right", , , , , "D"
return
}
```

**Comment by amirf147** [comment]
It could have been that your previous code would have worked if I had just changed:
`SendMode Input` to `SendMode "Input"` But I had already made the other changes before I changed that to get it to work. Because this works for me now, it's good enough for me at the moment.

**Comment by amirf147** [comment]
> The double dash's are not an issue with WSR, only VS Code. Have you tried setting VS Code to a different type of syntax highlighting? Are you on XML?

I received the error notification from windows speech recognition macros itself. I wonder if it has something to do with UTF 8 encoding which I am using. By the way, I never did find a way to support UTF 16 encoding. I even did install the Hebrew language pack and restarted the computer but I was still getting the encoding error. I also did make sure that I was saving appropriately using notepad and encoding option. Another avenue to explore if somebody else has this problem would be to try running the program with compatibility mode enabled this see if that fixes the encoding problem. As for me, keeping it at UTF 8 and not needing the Hebrew or other special characters and having compatibility mode turned off (as is by default) is working for me so far as I'm testing certain sections of your macros file separately.

**Comment by leeorhelps** [comment]
I really can't remember what I did to turn on UTF-16, but think it was one of these:

https://helpcenter.nshift.com/hc/article_attachments/360017209459/mceclip0.png


And/or


https://technoresult.com/how-to-change-default-encoding-in-notepad/


And/or if all else fails...


https://www.google.com.sg/search?q=change+utf+16+windows+control+panel

**Comment by leeorhelps** [comment]
Looks like you are successfully putting all the pieces together. 

Managed to get drag and drop working with AHK's help?

Exciting!
